[build]
  # 构建命令
  command = "npm run build"
  
  # 发布目录
  publish = "out"
  
  # 函数目录
  functions = "netlify/functions"

# Functions配置
[functions]
  # 设置函数超时时间为25秒（Netlify最大值）
  timeout = 25

[build.environment]
  # Node.js版本
  NODE_VERSION = "18"
  
  # 启用Next.js静态导出
  NEXT_TELEMETRY_DISABLED = "1"

# SPA重定向规则
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 头部设置 - 安全性和性能优化
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 静态文件缓存
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API路由处理
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 环境变量（在Netlify UI中设置）
# SILICONFLOW_API_KEY = "your_api_key_here"
# SILICONFLOW_API_URL = "https://api.siliconflow.cn/v1/chat/completions"
# SILICONFLOW_MODEL = "Qwen/Qwen3-235B-A22B" 